// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOsJbc4P0Pc-VJmplioS5peMToNIbX6Ko',
    appId: '1:382061897506:web:b750f6b0fdcd1e300de77b',
    messagingSenderId: '382061897506',
    projectId: 'chat-app-8a1da',
    authDomain: 'chat-app-8a1da.firebaseapp.com',
    storageBucket: 'chat-app-8a1da.firebasestorage.app',
    measurementId: 'G-72XR48YWEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyU3b9EwHS9A1isFro0exm_gkDA04KUI',
    appId: '1:382061897506:android:40eec9d4dd195e950de77b',
    messagingSenderId: '382061897506',
    projectId: 'chat-app-8a1da',
    storageBucket: 'chat-app-8a1da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMUU0UKYe2G_oI55m0CmIWSSgNkEFoDIA',
    appId: '1:382061897506:ios:4128135cea03770b0de77b',
    messagingSenderId: '382061897506',
    projectId: 'chat-app-8a1da',
    storageBucket: 'chat-app-8a1da.firebasestorage.app',
    iosBundleId: 'com.example.chatappWithFirebase',
  );
}
